# -*- coding: utf-8 -*-
"""2_2taxform.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f4u5h3D3eDLfCyw7R3HMFBH0F9PtYihc
"""

# -*- coding: utf-8 -*-
"""
Program: taxform.py
Author: Valeri Paul
Purpose:  Calculate Personal Income Tax. Week 2 2.2 Case Study
1. Significant constants
	  tax rate
	  standard deduction
	  deduction per dependent
2. The inputs are
	  gross income
		number of dependents
3. Compute:
  	taxable income = gross income - the standard deduction
		  - a deduction for each dependent
  	income tax = is a fixed percentage of the taxable income
4. The outputs are
	    the income tax owed or refunded
      
      Note:  The real challenge is coming up with sets of inputs that reveal
			an error.
  """
import pandas as pd

#Initialize the constants
TAX_RATE = 0.20
STANDARD_DEDUCTION = 10000.0
DEPENDENT_DEDUCTION = 3000.0


#Request the inputs
grossIncome = float(input("Enter the gross income:"))
numDependents = int(input("Enter the number of dependents:"))


#Compute the income tax
taxableIncome = grossIncome - STANDARD_DEDUCTION -\
	DEPENDENT_DEDUCTION * numDependents
incomeTax = taxableIncome * TAX_RATE

#Display the income tax
print("The income tax is $"+ str(incomeTax))
pause = str(input("Click enter to close") )
print(pause)