# -*- coding: utf-8 -*-
"""Copy of 2.8LightYear.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XViLE7yPDNlVAt8bDYCdcCuJL0sdvGeZ
"""

# -*- coding: utf-8 -*-
"""
Program: 2.8lightyear.py
ISTM 631 Professor Arash Vafanejad
Week 2 Project 2.8
Author: Valeri Paul
Project 2.8 ISTM 631 Light travels at 3 * 108 meters per second.
    A light year is the distance a light beam travels in one year.
   This is a program to compute or calculate and display the value of a light year.

Science facts:
   rate = 3 * 10 ** 8 meters per second
   seconds in a year = 365 * 24 * 60 ** 2

"""         

# Compute the result
rate = 3 * 10 ** 8
seconds = 365 * 24 * 60 ** 2
distance = rate * seconds

# Display the result
print("Light travels", distance, "meters in a year.")

